version: 0.1.{build}
branches:
  only:
  - master
skip_branch_with_pr: true
image: Visual Studio 2019
configuration: Release
shallow_clone: true
init:
  - cmd: dotnet --version
  - ps: 'if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { & dotnet tool install -g dotnet-sonarscanner }'
dotnet_csproj:
  patch: true 
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  project_feed: true 
before_build: 
  - ps: dotnet restore 
build_script:
  # Begin SonarScanner
  - ps: 'if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { & dotnet sonarscanner begin /k:"FluentAssertions.Web" /d:sonar.organization="adrianiftode-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:SONAR_TOKEN" /v:"$env:APPVEYOR_BUILD_NUMBER" }'
  - dotnet pack --no-restore
test_script:
  - dotnet test --no-restore
after_test:
  - ps: 'if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { & dotnet sonarscanner end /d:sonar.login="$env:SONAR_TOKEN" }'
artifacts:
  path: '**\*.nupkg'
  name: NuGet
deploy:
  provider: NuGet
  api_key:
    secure: +gGU9iifFY4osTq2ZOq/V1Nj2XR6yBawXYT61Gql2/PRtZ9ORjuFvAmr9E52ZIBB
  skip_symbols: false
  artifact: /.*\.nupkg/
  on: 
    branch: master