version: 1.1.{build}
image: Visual Studio 2022
branches:
  only:
  - master
pull_requests:
  do_not_increment_build_number: true
configuration: Release
shallow_clone: true
#environment:
#    COVERALLS_REPO_TOKEN:
#        secure: SflouAAf3PpL3Rb4aRbOhQEjZSfyaccBKst05kN6TQhJ2OCupXCUzzEdx1uzFI6j

skip_commits:
  files:
    - '**/*.md'
    - .gitignore
    - .editorconfig
    - samples/**/*
  message: /.*skip\sci.*/

init:
  - cmd: dotnet --version
  - ps: 'if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { & dotnet tool install -g dotnet-sonarscanner }'
  - cmd: dotnet tool install -g minicover
dotnet_csproj:
  patch: true 
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  project_feed: true 
before_build: 
  - dotnet restore
build_script:
  # Begin SonarScanner
  # Ensure Java 15, required by Sonar
  - set JAVA_HOME=C:\Program Files\Java\jdk15
  - if not exist "%JAVA_HOME%\bin\java.exe" (echo "%JAVA_HOME%\bin\java.exe does not exist" && exit 1)
  - set PATH=%JAVA_HOME%\bin;%PATH%
  - ps: 'if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { & dotnet sonarscanner begin /k:"FluentAssertions.Web" /o:adrianiftode-github /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:SONAR_TOKEN" /v:"$env:APPVEYOR_BUILD_NUMBER" /d:sonar.cs.opencover.reportsPaths="opencovercoverage.xml" /d:sonar.coverage.exclusions=test/**}'
  - dotnet build
  - minicover instrument
test_script:
  - dotnet test --no-restore --no-build
after_test:
  - minicover uninstrument
  - minicover opencoverreport
  # will fail when the test coverage is lower than the threshold
  - minicover report --threshold 95
  - ps: 'if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { & dotnet sonarscanner end /d:sonar.login="$env:SONAR_TOKEN" }'
  - dotnet pack --no-restore --include-symbols -c %CONFIGURATION%

artifacts:
  - path: '**\*.nupkg'
    name: NuGet

deploy:
  - provider: NuGet
    api_key:
        secure: dQssSGAckt6KCAeMrLKt0y2ZqQimWj2kRHS33F0zduvoV5sHG0TA1U3XmjdVuXnx
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
        branch: master